telegram_token: ${7902970696:AAHHeKuo1ZZx3bO8TbBCAAGJCWcQO5P6Cgs}
openai_key: ${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}
